### ISSUE TITLE
Why do we have -Wno-missing-exported-signatures?

### ISSUE THREAD

**Issue by kirelagin** [serokell/metatemplates#17]
We enable `-Weverything` and then explicitly disable some warnings.

In particular, we have `-Wno-missing-exported-signatures`.

Why do we have it? I’m pretty sure we actually _do_ want all exported symbols to have signatures. I also suspect this thing is useless, since we do not have `-Wmissing-signatures`, which means, we will still get warnings for any top-level symbol, exported or not.

**Comment by kirelagin** [comment]
cc @gromakovsky

**Comment by gromakovsky** [comment]
The source is https://medium.com/mercury-bank/enable-all-the-warnings-a0517bc081c3. You can read it fully if you want, but the author reported [this ticket](https://gitlab.haskell.org/ghc/ghc/-/issues/14794) which explains the reasoning. Usually we include the link to that Medium post in comments somewhere close to this list of warnings, however, I didn't include it into metatemplates' `package.yaml` because, I don't know, I guess I just got tired of seeing it everywhere :) 

So I think we should add https://medium.com/mercury-bank/enable-all-the-warnings-a0517bc081c3 link or at least https://gitlab.haskell.org/ghc/ghc/-/issues/14794. Also I wonder whether it's legal to copy-paste this list of flags from that post. Hopefully it's a small enough piece of code to keep everyone calm.

**Comment by kirelagin** [comment]
Regarding your last question, I dont’t think anyone would ever be able to prove that a list of compiler options can be viewed as a creative work.
